### ISSUE TITLE
 Unable to install du to changes in MariDB 10.6.0

### ISSUE THREAD

**Issue by Claes-Pontusson** [concretecms/addon_migration_tool#101]
Due to the addition of [offset as a reserved word in MariaDB 10.6.0](https://mariadb.com/kb/en/reserved-words/) the install fails.

This error is from a vanilla Concrete CMS 9.13.

An exception occurred while executing 'CREATE TABLE MigrationImportAreaLayoutColumns (id CHAR(36) NOT NULL COMMENT ‘(DC2Type:guid)’, area_layout_id CHAR(36) DEF

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version

**Comment by hissy** [comment]
@Claes-Pontusson 

Please use https://github.com/concretecms/migration_tool if you want to install migration tool on version 9

**Comment by Claes-Pontusson** [comment]
Ok. Thanks for pointing that out. 

The error is still the same though. Will post an issue in the other repo as well.

**Comment by hissy** [comment]
@aembler Let's pick this commit to this repository also
https://github.com/concretecms/migration_tool/pull/34

**Comment by Saggre** [comment]
Encountered the same issue. Here's a PR: https://github.com/concretecms/addon_migration_tool/pull/106
